const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
const W=800,H=560,T=40;let cols=20+4*Number(localStorage.dungeonSize||0),rows=14+2*Number(localStorage.dungeonSize||0);
const spells=[{name:'Moon Bolt',icon:'☄',desc:'Fast, focused damage',color:'#8362c6',damage:34,cool:420},{name:'Ember Ring',icon:'✹',desc:'Close-range splash',color:'#f1886d',damage:26,cool:600},{name:'Vine Snare',icon:'❋',desc:'Slows every foe',color:'#3d8c72',damage:16,cool:760}];
let state,keys={},last=0,runStarted=Date.now(),muted=false,aimX=1,aimY=0,moveAimX=1,moveAimY=0,lastMoveX=2.5,lastMoveY=7.5,playerHitCooldown=0,blocking=false,blockX=0,blockY=0,rendering=false, wallet=Number(localStorage.wallet||0),spellPower=Number(localStorage.spellPower||0),hpUpgrade=Number(localStorage.hpUpgrade||0),dungeonSize=Number(localStorage.dungeonSize||0),theme=Number(localStorage.theme||0),nextEnemyId=1,enemyLedger=new Set();
function fresh(){let map=Array.from({length:rows},()=>Array(cols).fill(1));const carve=(x1,y1,x2,y2)=>{for(let y=y1;y<=y2;y++)for(let x=x1;x<=x2;x++)map[y][x]=0};const rooms=[{x:1,y:5,w:4,h:4},{x:15,y:5,w:4,h:4}];for(let i=0;i<4+dungeonSize;i++)rooms.splice(1,0,{x:6+Math.floor(Math.random()*8),y:2+Math.floor(Math.random()*8),w:3+Math.floor(Math.random()*3),h:3+Math.floor(Math.random()*3)});rooms.forEach(r=>carve(r.x,r.y,Math.min(18,r.x+r.w-1),Math.min(12,r.y+r.h-1)));for(let i=0;i<rooms.length-1;i++){let a=rooms[i],b=rooms[i+1],ax=a.x+Math.floor(a.w/2),ay=a.y+Math.floor(a.h/2),bx=b.x+Math.floor(b.w/2),by=b.y+Math.floor(b.h/2);for(let x=Math.min(ax,bx);x<=Math.max(ax,bx);x++)map[ay][x]=0;for(let y=Math.min(ay,by);y<=Math.max(ay,by);y++)map[y][bx]=0}return{floor:1,rooms:0,hp:100+hpUpgrade,maxHp:100+hpUpgrade,x:2.5,y:7.5,dir:1,enemies:[],boss:null,projectiles:[],particles:[],traps:[],bossSpot:{x:17.5,y:7.5},spell:0,cooldown:0,map,over:false,win:false}};
function spawn(){state.enemies=[];state.traps=[];let count=Math.min(2+state.floor,7);for(let i=0;i<count;i++){let p=freeSpot();state.enemies.push({id:nextEnemyId++,x:p.x,y:p.y,hp:40+state.floor*8,max:40+state.floor*8,hit:0,slow:0})}enemyLedger=new Set(state.enemies.map(e=>e.id));for(let i=0;i<Math.min(2+state.floor,6);i++){let p=freeSpot();state.traps.push({x:p.x,y:p.y,armed:true})}state.boss=null;document.getElementById('objective').textContent='CLEAR THE ROOM';updateUI()}
function freeSpot(){const reachable=[];const seen=new Set(),queue=[[Math.floor(state.x),Math.floor(state.y)]];while(queue.length){const [x,y]=queue.shift(),key=`${x},${y}`;if(seen.has(key)||state.map[y]?.[x]!==0)continue;seen.add(key);reachable.push({x:x+.5,y:y+.5});for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]])queue.push([x+dx,y+dy])}const choices=reachable.filter(p=>Math.hypot(p.x-state.x,p.y-state.y)>5&&!state.enemies.some(e=>Math.hypot(p.x-e.x,p.y-e.y)<1.5)&&!(state.traps||[]).some(t=>Math.hypot(p.x-t.x,p.y-t.y)<1.5));return (choices.length?choices:reachable).sort(()=>Math.random()-.5)[0]||{x:17.5,y:7.5}}
function nextFloor(){state.floor++;state.rooms++;state.maxHp=100+hpUpgrade;state.hp=Math.min(state.maxHp,state.hp+25);state.x=2.5;state.y=7.5;const dungeon=fresh();state.map=dungeon.map;state.bossSpot=dungeon.bossSpot;spawn();say(`Floor ${String(state.floor).padStart(2,'0')}. Bumbles keeps going.`)}
function say(t){document.getElementById('message').textContent=t}
function blocked(x,y){return x<.55||y<.55||x>cols-.55||y>rows-.55||state.map[Math.floor(y)]?.[Math.floor(x)]!==0}
function update(dt){if(state.over)return;let dx=(keys.d||keys.ArrowRight?1:0)-(keys.a||keys.ArrowLeft?1:0),dy=(keys.s||keys.ArrowDown?1:0)-(keys.w||keys.ArrowUp?1:0);if(dx||dy){let l=Math.hypot(dx,dy);dx/=l;dy/=l;let speed=keys.Shift?1.5:2.7;if(!blocked(state.x+dx*speed*dt,state.y))state.x+=dx*speed*dt;if(!blocked(state.x,state.y+dy*speed*dt))state.y+=dy*speed*dt;state.dir=dx||state.dir}state.cooldown=Math.max(0,state.cooldown-dt*1000);state.enemies.forEach(e=>{e.hit=Math.max(0,e.hit-dt);e.slow=Math.max(0,e.slow-dt);let d=Math.hypot(state.x-e.x,state.y-e.y);if(d<.65&&e.hit<=0&&!keys.Shift){hurt(6);e.hit=1.0}if(d<6&&d>.8){let sp=e.slow?0.25:.45;let ex=e.x+(state.x-e.x)/d*sp*dt,ey=e.y+(state.y-e.y)/d*sp*dt;if(!blocked(ex,e.y))e.x=ex;if(!blocked(e.x,ey))e.y=ey}});state.projectiles.forEach(p=>{p.x+=p.dx*dt*8;p.y+=p.dy*dt*8;p.life-=dt;state.enemies.forEach(e=>{if(Math.hypot(p.x-e.x,p.y-e.y)<.55&&p.life>0){e.hp-=p.damage;p.life=0;burst(e.x,e.y,p.color)}})});state.projectiles=state.projectiles.filter(p=>p.life>0&&!blocked(p.x,p.y));state.enemies=state.enemies.filter(e=>e.hp>0);if(!state.boss&&state.enemies.length===0){state.boss={x:17,y:7,hp:130+state.floor*25,max:130+state.floor*25,hit:0};document.getElementById('objective').textContent='DEFEAT THE BOSS';document.getElementById('bossReadout').style.display='flex';say('The boss is here. That was fast.')}if(state.boss){let b=state.boss;b.hit=Math.max(0,b.hit-dt);let d=Math.hypot(state.x-b.x,state.y-b.y);if(d<.8&&b.hit<=0&&!keys.Shift){hurt(12);b.hit=1}if(d<7&&d>.9){let sp=.3;let ex=b.x+(state.x-b.x)/d*sp*dt,ey=b.y+(state.y-b.y)/d*sp*dt;if(!blocked(ex,b.y))b.x=ex;if(!blocked(b.x,ey))b.y=ey}if(b.hp<=0){state.win=true;state.over=true;showModal('FLOOR CLEARED',`Bumbles made it through floor ${state.floor}. One more floor?`, 'GO DEEPER')}}updateUI()}
function hurt(n){state.hp-=n;burst(state.x,state.y,'#f1886d');if(state.hp<=0){state.hp=0;state.over=true;showModal('RUN OVER','The dentist still hasn’t called. Try a different route?','TRY AGAIN')}}
function cast(){if(state.over||state.cooldown>0)return;let s=spells[state.spell];state.cooldown=s.cool;let angle=state.dir>0?0:Math.PI;state.projectiles.push({x:state.x+state.dir*.4,y:state.y,dx:Math.cos(angle),dy:0,damage:s.damage+state.floor*2,life:1.1,color:s.color});if(state.spell===1){state.enemies.forEach(e=>{if(Math.hypot(e.x-state.x,e.y-state.y)<2)e.hp-=s.damage;});burst(state.x,state.y,s.color)}if(state.spell===2)state.enemies.forEach(e=>{if(Math.hypot(e.x-state.x,e.y-state.y)<3){e.hp-=s.damage;e.slow=2}});say(s.name+'!');render()}
function burst(x,y,color){for(let i=0;i<7;i++)state.particles.push({x,y,dx:(Math.random()-.5)*3,dy:(Math.random()-.5)*3,life:.5,color})}
function draw(){ctx.clearRect(0,0,W,H);for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){let wall=state.map[y][x];ctx.fillStyle=wall?'#37413e':'#63726a';ctx.fillRect(x*T,y*T,T,T);if(!wall){ctx.fillStyle=(x+y)%2?'#66776e':'#617068';ctx.fillRect(x*T+1,y*T+1,T-2,T-2)}else{ctx.fillStyle='#2e3835';ctx.fillRect(x*T+3,y*T+3,T-6,T-6);ctx.fillStyle='#414c48';ctx.fillRect(x*T+6,y*T+5,T-12,5)}}for(let p of state.particles){ctx.globalAlpha=Math.max(0,p.life*2);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x*T,p.y*T,4,0,7);ctx.fill();p.x+=p.dx*.02;p.y+=p.dy*.02;p.life-=.016}ctx.globalAlpha=1;state.enemies.forEach(e=>drawEnemy(e,'#f1886d'));if(state.boss)drawEnemy(state.boss,'#efc45f',true);state.projectiles.forEach(p=>{ctx.fillStyle=p.color;ctx.shadowBlur=12;ctx.shadowColor=p.color;ctx.beginPath();ctx.arc(p.x*T,p.y*T,7,0,7);ctx.fill();ctx.shadowBlur=0});drawPlayer();}
function drawEnemy(e,color,boss=false){ctx.save();ctx.translate(e.x*T,e.y*T);ctx.fillStyle='#202827';ctx.beginPath();ctx.arc(0,3,boss?17:12,0,7);ctx.fill();ctx.fillStyle=color;ctx.beginPath();ctx.arc(0,0,boss?15:10,0,7);ctx.fill();ctx.fillStyle='#fff';ctx.fillRect(-boss?7:5,-3,4,5);ctx.fillRect(boss?3:2,-3,4,5);ctx.fillStyle='#202827';ctx.fillRect(boss?6:4,-1,2,3);ctx.fillRect(boss?2:1,-1,2,3);ctx.restore();ctx.fillStyle='#303b37';ctx.fillRect((e.x-(boss?1.2:.55))*T,(e.y-(boss?1.45:.8))*T,(boss?2.4:1.1)*T,3);ctx.fillStyle=color;ctx.fillRect((e.x-(boss?1.2:.55))*T,(e.y-(boss?1.45:.8))*T,(boss?2.4:1.1)*T*(e.hp/e.max),3)}
function drawPlayer(){let x=state.x*T,y=state.y*T;ctx.save();ctx.translate(x,y);ctx.fillStyle='#283332';ctx.beginPath();ctx.arc(0,5,14,0,7);ctx.fill();ctx.fillStyle='#a9dfc8';ctx.beginPath();ctx.arc(0,0,13,0,7);ctx.fill();ctx.fillStyle='#f5d9be';ctx.beginPath();ctx.arc(state.dir>0?3:-3,-6,7,0,7);ctx.fill();ctx.fillStyle='#202827';ctx.beginPath();ctx.arc(state.dir>0?5:-5,-7,2,0,7);ctx.fill();ctx.restore()}
function render(){draw();requestAnimationFrame(render)}
function updateUI(){document.getElementById('healthBar').style.width=(state.hp/state.maxHp*100)+'%';document.getElementById('healthText').textContent=`${Math.ceil(state.hp)} / ${state.maxHp}`;document.getElementById('floorValue').textContent=String(state.floor).padStart(2,'0');document.getElementById('roomsValue').textContent=state.rooms;document.getElementById('bestValue').textContent=String(Math.max(state.floor,+(localStorage.bestFloor||1))).padStart(2,'0');document.getElementById('enemyCount').textContent=state.enemies.length+(state.boss?' + boss':'')+' enemies';if(state.boss){document.getElementById('bossBar').style.width=(state.boss.hp/state.boss.max*100)+'%'}document.querySelectorAll('.spell-slot').forEach((e,i)=>e.classList.toggle('active',i===state.spell))}
function showModal(title,text,button){document.getElementById('modalTitle').textContent=title;document.getElementById('modalText').textContent=text;document.getElementById('modalBtn').textContent=button;document.getElementById('overlay').classList.remove('hidden')}
function setup(){state=fresh();spawn();document.getElementById('spellSlots').innerHTML=spells.map((s,i)=>`<button class="spell-slot ${i?'':'active'}" data-spell="${i}" style="color:${s.color}">${s.icon}<small>${i+1}</small></button>`).join('');document.getElementById('spellList').innerHTML=spells.map((s,i)=>`<div class="spell-choice ${i?'':'selected'}" data-choice="${i}"><span class="spell-icon" style="background:${s.color}">${s.icon}</span><div><b>${s.name}</b><p>${s.desc}<br><span class="eyebrow">KEY ${i+1}</span></p></div></div>`).join('');document.querySelectorAll('[data-spell],[data-choice]').forEach(e=>e.onclick=()=>{state.spell=e.dataset.spell!==undefined?Number(e.dataset.spell):Number(e.dataset.choice);document.querySelectorAll('.spell-choice').forEach((x,i)=>x.classList.toggle('selected',i===state.spell));updateUI()});}
addEventListener('keydown',e=>{keys[e.key]=true;if(e.key===' ') {e.preventDefault();cast()}if(/^\d$/.test(e.key)&&+e.key<=3){state.spell=+e.key-1;updateUI()}});addEventListener('keyup',e=>keys[e.key]=false);document.getElementById('mobileCast').onclick=cast;document.querySelectorAll('[data-key]').forEach(b=>{b.addEventListener('touchstart',e=>{e.preventDefault();keys[b.dataset.key]=true});b.addEventListener('touchend',()=>keys[b.dataset.key]=false)});document.getElementById('modalBtn').onclick=()=>{document.getElementById('overlay').classList.add('hidden');if(state.win){localStorage.bestFloor=Math.max(state.floor,+(localStorage.bestFloor||1));state.over=false;state.win=false;nextFloor()}else setup()};document.getElementById('soundBtn').onclick=()=>{muted=!muted;document.getElementById('soundBtn').textContent=muted?'♩':'♫'};setInterval(()=>{let s=Math.floor((Date.now()-runStarted)/1000);document.getElementById('runTime').textContent=`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`},1000);setup();function loop(t){update(Math.min(.04,(t-last)/1000||0));last=t;requestAnimationFrame(loop)}requestAnimationFrame(loop);render();

// The most recently pressed direction controls where the next spell travels.
addEventListener('keydown',e=>{const dirs={w:[0,-1],ArrowUp:[0,-1],s:[0,1],ArrowDown:[0,1],a:[-1,0],ArrowLeft:[-1,0],d:[1,0],ArrowRight:[1,0]};if(dirs[e.key]){[aimX,aimY]=dirs[e.key]}});
document.querySelectorAll('[data-key]').forEach(button=>button.addEventListener('touchstart',()=>{const dirs={ArrowUp:[0,-1],ArrowDown:[0,1],ArrowLeft:[-1,0],ArrowRight:[1,0]};if(dirs[button.dataset.key]) [aimX,aimY]=dirs[button.dataset.key]}));
function cast(){if(state.over||state.cooldown>0)return;let s=spells[state.spell];state.cooldown=s.cool;state.projectiles.push({x:state.x+aimX*.4,y:state.y+aimY*.4,dx:aimX,dy:aimY,damage:s.damage+state.floor*2,life:1.1,color:s.color});if(state.spell===1){state.enemies.forEach(e=>{if(Math.hypot(e.x-state.x,e.y-state.y)<2)e.hp-=s.damage});burst(state.x,state.y,s.color)}if(state.spell===2)state.enemies.forEach(e=>{if(Math.hypot(e.x-state.x,e.y-state.y)<3){e.hp-=s.damage;e.slow=2}});say(s.name+'!');render()}

addEventListener('keydown',e=>{if(e.key==='Shift'&&!blocking){blocking=true;blockX=state.x;blockY=state.y}});
addEventListener('keyup',e=>{if(e.key==='Shift'){blocking=false;['w','a','s','d','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].forEach(key=>keys[key]=false)}});
addEventListener('blur',()=>{keys={};blocking=false});
setInterval(()=>{if(!state)return;blocking=!!keys.Shift;if(blocking&&!state.over){state.x=blockX;state.y=blockY}},10);
setInterval(()=>{if(!state||state.over)return;if(blocking){lastMoveX=state.x;lastMoveY=state.y;return}let dx=state.x-lastMoveX,dy=state.y-lastMoveY,d=Math.hypot(dx,dy);if(d>.001){moveAimX=dx/d;moveAimY=dy/d;lastMoveX=state.x;lastMoveY=state.y}},10);
let wallBump=0;
setInterval(()=>{if(!state||state.over||blocking){wallBump=0;return}let dx=(keys.d||keys.ArrowRight?1:0)-(keys.a||keys.ArrowLeft?1:0),dy=(keys.s||keys.ArrowDown?1:0)-(keys.w||keys.ArrowUp?1:0);if(!dx&&!dy){wallBump=0;return}let tx=Math.floor(state.x)+Math.sign(dx),ty=Math.floor(state.y)+Math.sign(dy),nx=tx+Math.sign(dx),ny=ty+Math.sign(dy),one=state.map[ty]?.[tx],two=state.map[ny]?.[nx];if(one!==0&&two===0){wallBump++;if(wallBump>8){state.map[ty][tx]=0;wallBump=0;say('Path cleared.');render()}}else wallBump=0},50);

// Keep boss hits and contact damage independent of the room-clear loop.
setInterval(()=>{if(!state||state.over)return;playerHitCooldown=Math.max(0,playerHitCooldown-0.05);state.projectiles.forEach(p=>{if(state.boss&&p.life>0&&Math.hypot(p.x-state.boss.x,p.y-state.boss.y)<.7){state.boss.hp-=p.damage;p.life=0;burst(state.boss.x,state.boss.y,p.color)}});if(playerHitCooldown===0){let touching=state.enemies.some(e=>Math.hypot(e.x-state.x,e.y-state.y)<.75)||(state.boss&&Math.hypot(state.boss.x-state.x,state.boss.y-state.y)<.9);if(touching){hurt(state.boss&&Math.hypot(state.boss.x-state.x,state.boss.y-state.y)<.9?12:6);playerHitCooldown=.75}}},50);

// Traps can be safely disarmed from a distance, or triggered by stepping on them.
setInterval(()=>{if(!state||state.over)return;state.traps.forEach(t=>{if(t.armed&&Math.hypot(t.x-state.x,t.y-state.y)<.55){t.armed=false;hurt(14);say('Ouch. Trap triggered!')}});state.projectiles.forEach(p=>state.traps.forEach(t=>{if(t.armed&&p.life>0&&Math.hypot(p.x-t.x,p.y-t.y)<.6){t.armed=false;p.life=0;burst(t.x,t.y,'#efc45f');say('Trap disarmed.')}}))},50);

function drawPlayer(){if(state.traps)state.traps.forEach(t=>{ctx.save();ctx.translate(t.x*T,t.y*T);ctx.strokeStyle=t.armed?'#efc45f':'#708078';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,11,0,Math.PI*2);ctx.stroke();if(t.armed){ctx.fillStyle='#efc45f';for(let i=0;i<4;i++){let a=i*Math.PI/2+.4;ctx.beginPath();ctx.moveTo(Math.cos(a)*4,Math.sin(a)*4);ctx.lineTo(Math.cos(a)*12,Math.sin(a)*12);ctx.stroke()}}else{ctx.fillStyle='#708078';ctx.fillRect(-6,-2,12,4)}ctx.restore()});let x=state.x*T,y=state.y*T;ctx.save();ctx.translate(x,y);ctx.fillStyle='#283332';ctx.beginPath();ctx.arc(0,5,14,0,7);ctx.fill();ctx.fillStyle='#a9dfc8';ctx.beginPath();ctx.arc(0,0,13,0,7);ctx.fill();ctx.fillStyle='#f5d9be';ctx.beginPath();ctx.arc(state.dir>0?3:-3,-6,7,0,7);ctx.fill();ctx.fillStyle='#202827';ctx.beginPath();ctx.arc(state.dir>0?5:-5,-7,2,0,7);ctx.fill();ctx.restore()}

function earn(amount){wallet+=amount;localStorage.wallet=wallet;updateUI()}
function applyTheme(){const filters=['none','sepia(.7) hue-rotate(70deg) saturate(1.25)','sepia(.45) hue-rotate(165deg) saturate(1.4)'];canvas.style.filter=filters[theme%filters.length]}
function buy(item){const prices={power:12,hp:18,size:25,theme:10};if(wallet<prices[item]){say('Need more ◆. Keep exploring.');return}wallet-=prices[item];if(item==='power')spellPower+=10;if(item==='hp')hpUpgrade+=20;if(item==='size')dungeonSize=Math.min(3,dungeonSize+1);if(item==='theme')theme=(theme+1)%3;localStorage.wallet=wallet;localStorage.spellPower=spellPower;localStorage.hpUpgrade=hpUpgrade;localStorage.dungeonSize=dungeonSize;localStorage.theme=theme;applyTheme();if(item==='hp'){state.maxHp+=20;state.hp+=20}if(item==='size'||item==='theme')say(item==='size'?'The next floor will be bigger.':'New map colors unlocked.');updateUI()}
function updateUI(){document.getElementById('healthBar').style.width=(state.hp/state.maxHp*100)+'%';document.getElementById('healthText').textContent=`${Math.ceil(state.hp)} / ${state.maxHp}`;document.getElementById('floorValue').textContent=String(state.floor).padStart(2,'0');document.getElementById('roomsValue').textContent=state.rooms;document.getElementById('bestValue').textContent=String(Math.max(state.floor,+(localStorage.bestFloor||1))).padStart(2,'0');document.getElementById('enemyCount').textContent=state.enemies.length+(state.boss?' + boss':'')+' enemies';document.getElementById('moneyValue').textContent=`◆ ${wallet}`;if(state.boss)document.getElementById('bossBar').style.width=(state.boss.hp/state.boss.max*100)+'%';document.querySelectorAll('.spell-slot').forEach((e,i)=>e.classList.toggle('active',i===state.spell));applyTheme()}
document.querySelectorAll('[data-buy]').forEach(button=>button.addEventListener('click',()=>buy(button.dataset.buy)));
setInterval(()=>{if(!state||state.over)return;state.enemies.forEach(e=>enemyLedger.add(e.id));for(const id of [...enemyLedger])if(!state.enemies.some(e=>e.id===id)){enemyLedger.delete(id);earn(5);say('+5 ◆ enemy defeated')}state.traps.forEach(t=>{if(!t.armed&&!t.rewarded){t.rewarded=true;earn(3);say('+3 ◆ trap cleared')}})},100);
function cast(){if(state.over||state.cooldown>0)return;let s=spells[state.spell],damage=s.damage+state.floor*2+spellPower;state.cooldown=s.cool;state.projectiles.push({x:state.x+aimX*.4,y:state.y+aimY*.4,dx:aimX,dy:aimY,damage,life:1.1,color:s.color});if(state.spell===1){state.enemies.forEach(e=>{if(Math.hypot(e.x-state.x,e.y-state.y)<2)e.hp-=damage});burst(state.x,state.y,s.color)}if(state.spell===2)state.enemies.forEach(e=>{if(Math.hypot(e.x-state.x,e.y-state.y)<3){e.hp-=damage;e.slow=2}});say(s.name+'!');render()}

function expandDungeon(){for(let n=0;n<dungeonSize;n++){let cx=6+Math.floor(Math.random()*8),cy=2+Math.floor(Math.random()*9);for(let y=Math.max(1,cy-1);y<=Math.min(rows-2,cy+2);y++)for(let x=Math.max(1,cx-2);x<=Math.min(cols-2,cx+2);x++)state.map[y][x]=0;for(let x=Math.min(5,cx);x<=Math.max(5,cx);x++)state.map[7][x]=0;for(let y=Math.min(7,cy);y<=Math.max(7,cy);y++)state.map[y][cx]=0}}
function buy(item){const prices={power:12,hp:18,size:25,theme:10};if(wallet<prices[item]){say('Need more ◆. Keep exploring.');return}wallet-=prices[item];if(item==='power')spellPower+=10;if(item==='hp'){hpUpgrade+=20;state.maxHp+=20;state.hp+=20}if(item==='size'){dungeonSize=Math.min(3,dungeonSize+1);expandDungeon();state.x=2.5;state.y=7.5;spawn();say('Dungeon expanded. New rooms opened!')}if(item==='theme')theme=(theme+1)%3;localStorage.wallet=wallet;localStorage.spellPower=spellPower;localStorage.hpUpgrade=hpUpgrade;localStorage.dungeonSize=dungeonSize;localStorage.theme=theme;applyTheme();updateUI()}

// Regenerate the actual board at the purchased grid dimensions.
function fresh(){cols=20+4*dungeonSize;rows=14+2*dungeonSize;canvas.width=cols*T;canvas.height=rows*T;let map=Array.from({length:rows},()=>Array(cols).fill(1));const carve=(x1,y1,x2,y2)=>{for(let y=Math.max(1,y1);y<=Math.min(rows-2,y2);y++)for(let x=Math.max(1,x1);x<=Math.min(cols-2,x2);x++)map[y][x]=0};const endX=cols-6;const rooms=[{x:1,y:5,w:4,h:4},{x:endX,y:5,w:5,h:4}];for(let i=0;i<4+dungeonSize;i++)rooms.splice(1,0,{x:5+Math.floor(Math.random()*Math.max(1,cols-12)),y:2+Math.floor(Math.random()*Math.max(1,rows-6)),w:3+Math.floor(Math.random()*3),h:3+Math.floor(Math.random()*3)});rooms.forEach(r=>carve(r.x,r.y,r.x+r.w-1,r.y+r.h-1));for(let i=0;i<rooms.length-1;i++){let a=rooms[i],b=rooms[i+1],ax=a.x+Math.floor(a.w/2),ay=a.y+Math.floor(a.h/2),bx=b.x+Math.floor(b.w/2),by=b.y+Math.floor(b.h/2);for(let x=Math.min(ax,bx);x<=Math.max(ax,bx);x++)map[ay][x]=0;for(let y=Math.min(ay,by);y<=Math.max(ay,by);y++)map[y][bx]=0}return{floor:1,rooms:0,hp:100+hpUpgrade,maxHp:100+hpUpgrade,x:2.5,y:7.5,dir:1,enemies:[],boss:null,projectiles:[],particles:[],traps:[],bossSpot:{x:endX+2.5,y:7.5},spell:0,cooldown:0,map,over:false,win:false}}
function buy(item){const prices={power:12,hp:18,size:25,theme:10};if(wallet<prices[item]){say('Need more ◆. Keep exploring.');return}wallet-=prices[item];if(item==='power')spellPower+=10;if(item==='hp'){hpUpgrade+=20;state.maxHp+=20;state.hp+=20}if(item==='size'){dungeonSize=Math.min(3,dungeonSize+1);const dungeon=fresh();state.map=dungeon.map;state.bossSpot=dungeon.bossSpot;state.x=2.5;state.y=7.5;spawn();say(`Board expanded to ${cols} × ${rows}!`)}if(item==='theme')theme=(theme+1)%3;localStorage.wallet=wallet;localStorage.spellPower=spellPower;localStorage.hpUpgrade=hpUpgrade;localStorage.dungeonSize=dungeonSize;localStorage.theme=theme;applyTheme();updateUI()}
setInterval(()=>{if(state&&state.boss&&state.bossSpot&&!state.boss.placed){state.boss.x=state.bossSpot.x;state.boss.y=state.bossSpot.y;state.boss.placed=true}},50);
function cast(){if(state.over||state.cooldown>0)return;let s=spells[state.spell],damage=s.damage+state.floor*2+spellPower;state.cooldown=s.cool;state.projectiles.push({x:state.x+moveAimX*.4,y:state.y+moveAimY*.4,dx:moveAimX,dy:moveAimY,damage,life:1.1,color:s.color});if(state.spell===1){state.enemies.forEach(e=>{if(Math.hypot(e.x-state.x,e.y-state.y)<2)e.hp-=damage});burst(state.x,state.y,s.color)}if(state.spell===2)state.enemies.forEach(e=>{if(Math.hypot(e.x-state.x,e.y-state.y)<3){e.hp-=damage;e.slow=2}});say(s.name+'!');render()}

function spawn(){state.enemies=[];state.traps=[];state.enemyShots=[];let count=Math.min(2+state.floor,12);for(let i=0;i<count;i++){let p=freeSpot(),ranged=Math.random()<Math.min(.35,.12+state.floor*.025);state.enemies.push({id:nextEnemyId++,x:p.x,y:p.y,hp:40+state.floor*8,max:40+state.floor*8,hit:0,slow:0,type:ranged?'ranged':'melee',shootCooldown:.7+Math.random()})}enemyLedger=new Set(state.enemies.map(e=>e.id));for(let i=0;i<Math.min(2+state.floor,6);i++){let p=freeSpot();state.traps.push({x:p.x,y:p.y,armed:true})}state.boss=null;document.getElementById('objective').textContent='CLEAR THE ROOM';updateUI()}
setInterval(()=>{if(!state||state.over)return;state.enemyShots=state.enemyShots||[];state.enemies.forEach(e=>{if(e.type!=='ranged')return;e.shootCooldown-=.05;let d=Math.hypot(state.x-e.x,state.y-e.y);if(e.shootCooldown<=0&&d<10){e.shootCooldown=1.7;state.enemyShots.push({x:e.x,y:e.y,dx:(state.x-e.x)/d,dy:(state.y-e.y)/d,speed:3.4,damage:7,life:4,color:'#f1886d'})}});if(state.boss){state.boss.shootCooldown=(state.boss.shootCooldown||.5)-.05;let d=Math.hypot(state.x-state.boss.x,state.y-state.boss.y);if(state.boss.shootCooldown<=0&&d<13){state.boss.shootCooldown=1.15;state.enemyShots.push({x:state.boss.x,y:state.boss.y,dx:(state.x-state.boss.x)/d,dy:(state.y-state.boss.y)/d,speed:4,damage:15,life:4,color:'#efc45f'})}}state.enemyShots.forEach(p=>{p.x+=p.dx*p.speed*.05;p.y+=p.dy*p.speed*.05;p.life-=.05;if(Math.hypot(p.x-state.x,p.y-state.y)<.45){if(!keys.Shift)hurt(p.damage);p.life=0}if(blocked(p.x,p.y))p.life=0});state.enemyShots=state.enemyShots.filter(p=>p.life>0)},50);
setInterval(()=>{if(!state||state.over||!state.boss||state.boss.placed)return;let hp=180+state.floor*70;state.boss.hp=hp;state.boss.max=hp;state.boss.shootCooldown=.5},50);
function drawPlayer(){if(state.traps)state.traps.forEach(t=>{ctx.save();ctx.translate(t.x*T,t.y*T);ctx.strokeStyle=t.armed?'#efc45f':'#708078';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,11,0,Math.PI*2);ctx.stroke();if(t.armed){ctx.fillStyle='#efc45f';for(let i=0;i<4;i++){let a=i*Math.PI/2+.4;ctx.beginPath();ctx.moveTo(Math.cos(a)*4,Math.sin(a)*4);ctx.lineTo(Math.cos(a)*12,Math.sin(a)*12);ctx.stroke()}}else{ctx.fillStyle='#708078';ctx.fillRect(-6,-2,12,4)}ctx.restore()});(state.enemyShots||[]).forEach(p=>{ctx.fillStyle=p.color;ctx.shadowBlur=10;ctx.shadowColor=p.color;ctx.beginPath();ctx.arc(p.x*T,p.y*T,5,0,7);ctx.fill();ctx.shadowBlur=0});let x=state.x*T,y=state.y*T;ctx.save();ctx.translate(x,y);ctx.fillStyle='#283332';ctx.beginPath();ctx.arc(0,5,14,0,7);ctx.fill();ctx.fillStyle='#a9dfc8';ctx.beginPath();ctx.arc(0,0,13,0,7);ctx.fill();ctx.fillStyle='#f5d9be';ctx.beginPath();ctx.arc(state.dir>0?3:-3,-6,7,0,7);ctx.fill();ctx.fillStyle='#202827';ctx.beginPath();ctx.arc(state.dir>0?5:-5,-7,2,0,7);ctx.fill();ctx.restore()}
function drawEnemy(e,color,boss=false){ctx.save();ctx.translate(e.x*T,e.y*T);let ranged=e.type==='ranged'&&!boss;ctx.fillStyle='#202827';ctx.beginPath();ctx.arc(0,3,boss?17:12,0,7);ctx.fill();ctx.fillStyle=boss?'#efc45f':ranged?'#c779d8':color;ctx.beginPath();ctx.arc(0,0,boss?15:10,0,7);ctx.fill();ctx.fillStyle='#fff';ctx.fillRect(-5,-3,4,5);ctx.fillRect(2,-3,4,5);ctx.fillStyle='#202827';ctx.fillRect(-4,-1,2,3);ctx.fillRect(3,-1,2,3);if(ranged){ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,6,0,Math.PI*2);ctx.stroke()}ctx.restore();ctx.fillStyle='#303b37';ctx.fillRect((e.x-(boss?1.2:.55))*T,(e.y-(boss?1.45:.8))*T,(boss?2.4:1.1)*T,3);ctx.fillStyle=boss?'#efc45f':color;ctx.fillRect((e.x-(boss?1.2:.55))*T,(e.y-(boss?1.45:.8))*T,(boss?2.4:1.1)*T*(e.hp/e.max),3)}
setInterval(()=>{if(state&&state.boss&&!state.boss.hpScaled){let hp=180+state.floor*70;state.boss.hp=hp;state.boss.max=hp;state.boss.hpScaled=true;state.boss.shootCooldown=.5}},50);
function spawn(){state.enemies=[];state.traps=[];state.enemyShots=[];let count=Math.min(2+state.floor,12);for(let i=0;i<count;i++){let p=freeSpot(),ranged=i===0||Math.random()<Math.min(.35,.12+state.floor*.025);state.enemies.push({id:nextEnemyId++,x:p.x,y:p.y,hp:40+state.floor*8,max:40+state.floor*8,hit:0,slow:0,type:ranged?'ranged':'melee',shootCooldown:.7+Math.random()})}enemyLedger=new Set(state.enemies.map(e=>e.id));for(let i=0;i<Math.min(2+state.floor,6);i++){let p=freeSpot();state.traps.push({x:p.x,y:p.y,armed:true})}state.boss=null;document.getElementById('objective').textContent='CLEAR THE ROOM';updateUI()}
function render(){if(rendering)return;rendering=true;function frame(){draw();requestAnimationFrame(frame)}requestAnimationFrame(frame)}
setInterval(()=>{if(!state||state.over)return;state.enemies.forEach(e=>{let d=Math.hypot(state.x-e.x,state.y-e.y);if(d<6)return;e.roamTimer=(e.roamTimer||0)-.1;if(!e.roamX||e.roamTimer<=0||Math.hypot(e.roamX-e.x,e.roamY-e.y)<.35){for(let i=0;i<20;i++){let x=1.5+Math.random()*(cols-3),y=1.5+Math.random()*(rows-3);if(!blocked(x,y)&&Math.hypot(x-state.x,y-state.y)>5){e.roamX=x;e.roamY=y;e.roamTimer=2+Math.random()*3;break}}}let dx=e.roamX-e.x,dy=e.roamY-e.y,len=Math.hypot(dx,dy);if(len>.2){let speed=.22*(e.slow?0.5:1),nx=e.x+dx/len*speed,ny=e.y+dy/len*speed;if(!blocked(nx,e.y))e.x=nx;if(!blocked(e.x,ny))e.y=ny}})},100);
function render(){if(rendering)return;rendering=true;function frame(){draw();let viewport=document.querySelector('.game-frame');if(state&&viewport&&canvas.width>viewport.clientWidth){viewport.scrollLeft=Math.max(0,Math.min(state.x*T-viewport.clientWidth/2,canvas.width-viewport.clientWidth));viewport.scrollTop=Math.max(0,Math.min(state.y*T-viewport.clientHeight/2,canvas.height-viewport.clientHeight))}requestAnimationFrame(frame)}requestAnimationFrame(frame)}
function render(){if(rendering)return;rendering=true;function frame(){draw();let viewport=document.querySelector('.canvas-viewport');if(state&&viewport){let maxX=Math.max(0,canvas.width-viewport.clientWidth),maxY=Math.max(0,canvas.height-viewport.clientHeight);viewport.scrollLeft=Math.max(0,Math.min(state.x*T-viewport.clientWidth/2,maxX));viewport.scrollTop=Math.max(0,Math.min(state.y*T-viewport.clientHeight/2,maxY))}requestAnimationFrame(frame)}requestAnimationFrame(frame)}
function spawn(){state.enemies=[];state.traps=[];state.enemyShots=[];state.healthKits=[];let count=Math.min(2+state.floor,12);for(let i=0;i<count;i++){let p=freeSpot(),ranged=i===0||Math.random()<Math.min(.35,.12+state.floor*.025);state.enemies.push({id:nextEnemyId++,x:p.x,y:p.y,hp:40+state.floor*8,max:40+state.floor*8,hit:0,slow:0,type:ranged?'ranged':'melee',shootCooldown:.7+Math.random()})}enemyLedger=new Set(state.enemies.map(e=>e.id));for(let i=0;i<Math.min(2+state.floor,6);i++){let p=freeSpot();state.traps.push({x:p.x,y:p.y,armed:true})}for(let i=0;i<Math.floor(Math.random()*4);i++){let p=freeSpot();state.healthKits.push({x:p.x,y:p.y,active:true})}state.boss=null;document.getElementById('objective').textContent='CLEAR THE ROOM';updateUI()}
setInterval(()=>{if(!state||state.over)return;(state.healthKits||[]).forEach(k=>{if(k.active&&Math.hypot(k.x-state.x,k.y-state.y)<.65){k.active=false;state.hp=Math.min(state.maxHp,state.hp+20);say('+20 HP. Nice find.');updateUI()}})},50);
function drawPlayer(){if(state.healthKits)state.healthKits.forEach(k=>{if(!k.active)return;ctx.save();ctx.translate(k.x*T,k.y*T);ctx.fillStyle='#b7edc9';ctx.beginPath();ctx.roundRect(-11,-11,22,22,4);ctx.fill();ctx.fillStyle='#3d8c72';ctx.fillRect(-3,-8,6,16);ctx.fillRect(-8,-3,16,6);ctx.restore()});if(state.traps)state.traps.forEach(t=>{ctx.save();ctx.translate(t.x*T,t.y*T);ctx.strokeStyle=t.armed?'#efc45f':'#708078';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,11,0,Math.PI*2);ctx.stroke();if(t.armed){ctx.fillStyle='#efc45f';for(let i=0;i<4;i++){let a=i*Math.PI/2+.4;ctx.beginPath();ctx.moveTo(Math.cos(a)*4,Math.sin(a)*4);ctx.lineTo(Math.cos(a)*12,Math.sin(a)*12);ctx.stroke()}}else{ctx.fillStyle='#708078';ctx.fillRect(-6,-2,12,4)}ctx.restore()});(state.enemyShots||[]).forEach(p=>{ctx.fillStyle=p.color;ctx.shadowBlur=10;ctx.shadowColor=p.color;ctx.beginPath();ctx.arc(p.x*T,p.y*T,5,0,7);ctx.fill();ctx.shadowBlur=0});let x=state.x*T,y=state.y*T;ctx.save();ctx.translate(x,y);ctx.fillStyle='#283332';ctx.beginPath();ctx.arc(0,5,14,0,7);ctx.fill();ctx.fillStyle='#a9dfc8';ctx.beginPath();ctx.arc(0,0,13,0,7);ctx.fill();ctx.fillStyle='#f5d9be';ctx.beginPath();ctx.arc(state.dir>0?3:-3,-6,7,0,7);ctx.fill();ctx.fillStyle='#202827';ctx.beginPath();ctx.arc(state.dir>0?5:-5,-7,2,0,7);ctx.fill();ctx.restore()}
function spawn(){state.enemies=[];state.traps=[];state.enemyShots=[];state.healthKits=[];let count=Math.min(2+state.floor,12);for(let i=0;i<count;i++){let p=freeSpot(),ranged=i===0||Math.random()<Math.min(.35,.12+state.floor*.025);state.enemies.push({id:nextEnemyId++,x:p.x,y:p.y,hp:40+state.floor*8,max:40+state.floor*8,hit:0,slow:0,type:ranged?'ranged':'melee',shootCooldown:.7+Math.random()})}enemyLedger=new Set(state.enemies.map(e=>e.id));for(let i=0;i<Math.min(2+state.floor,6);i++){let p=freeSpot();state.traps.push({x:p.x,y:p.y,armed:true})}for(let i=0;i<Math.floor(Math.random()*4);i++){let p=freeSpot();state.healthKits.push({x:p.x,y:p.y,active:true})}let box=freeSpot(),target=freeSpot();state.sideQuest={npc:{x:2.5,y:4.5},box,target,carrying:false,accepted:false,done:false};state.boss=null;document.getElementById('objective').textContent='CLEAR THE ROOM';updateUI()}
setInterval(()=>{if(!state||state.over||!state.sideQuest)return;let q=state.sideQuest;if(!q.accepted&&Math.hypot(state.x-q.npc.x,state.y-q.npc.y)<1){q.accepted=true;say('Quest: deliver the box to the blue marker for +15 ◆')}if(q.accepted&&!q.done&&!q.carrying&&Math.hypot(state.x-q.box.x,state.y-q.box.y)<.75){q.carrying=true;say('Box picked up. Take it to the blue marker.')}if(q.carrying){q.box.x=state.x;q.box.y=state.y-.65;if(Math.hypot(state.x-q.target.x,state.y-q.target.y)<1){q.carrying=false;q.done=true;wallet+=15;localStorage.wallet=wallet;say('+15 ◆ sidequest complete!');updateUI()}}},50);
setInterval(()=>{if(state?.sideQuest&&blocked(state.sideQuest.npc.x,state.sideQuest.npc.y))state.sideQuest.npc.y=6.5},100);
function drawPlayer(){if(state.sideQuest){let q=state.sideQuest;ctx.save();ctx.translate(q.npc.x*T,q.npc.y*T);ctx.fillStyle='#8362c6';ctx.beginPath();ctx.arc(0,0,13,0,7);ctx.fill();ctx.fillStyle='#fff';ctx.font='bold 14px sans-serif';ctx.textAlign='center';ctx.fillText('?',0,5);ctx.restore();if(q.accepted&&!q.done){ctx.save();ctx.translate(q.target.x*T,q.target.y*T);ctx.strokeStyle='#79d5ff';ctx.lineWidth=3;ctx.setLineDash([5,4]);ctx.beginPath();ctx.arc(0,0,16,0,7);ctx.stroke();ctx.setLineDash([]);ctx.restore()}if(!q.carrying&&!q.done){ctx.save();ctx.translate(q.box.x*T,q.box.y*T);ctx.fillStyle='#b87845';ctx.fillRect(-13,-11,26,22);ctx.strokeStyle='#f0c27b';ctx.lineWidth=3;ctx.strokeRect(-9,-8,18,16);ctx.restore()}if(q.carrying){ctx.save();ctx.translate(state.x*T,(state.y-.65)*T);ctx.fillStyle='#b87845';ctx.fillRect(-12,-10,24,20);ctx.restore()}}if(state.healthKits)state.healthKits.forEach(k=>{if(!k.active)return;ctx.save();ctx.translate(k.x*T,k.y*T);ctx.fillStyle='#b7edc9';ctx.beginPath();ctx.roundRect(-11,-11,22,22,4);ctx.fill();ctx.fillStyle='#3d8c72';ctx.fillRect(-3,-8,6,16);ctx.fillRect(-8,-3,16,6);ctx.restore()});if(state.traps)state.traps.forEach(t=>{ctx.save();ctx.translate(t.x*T,t.y*T);ctx.strokeStyle=t.armed?'#efc45f':'#708078';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,11,0,7);ctx.stroke();if(t.armed){for(let i=0;i<4;i++){let a=i*Math.PI/2+.4;ctx.beginPath();ctx.moveTo(Math.cos(a)*4,Math.sin(a)*4);ctx.lineTo(Math.cos(a)*12,Math.sin(a)*12);ctx.stroke()}}ctx.restore()});(state.enemyShots||[]).forEach(p=>{ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x*T,p.y*T,5,0,7);ctx.fill()});let x=state.x*T,y=state.y*T;ctx.save();ctx.translate(x,y);ctx.fillStyle='#283332';ctx.beginPath();ctx.arc(0,5,14,0,7);ctx.fill();ctx.fillStyle='#a9dfc8';ctx.beginPath();ctx.arc(0,0,13,0,7);ctx.fill();ctx.fillStyle='#f5d9be';ctx.beginPath();ctx.arc(state.dir>0?3:-3,-6,7,0,7);ctx.fill();ctx.fillStyle='#202827';ctx.beginPath();ctx.arc(state.dir>0?5:-5,-7,2,0,7);ctx.fill();ctx.restore()}
